# Question 1

In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,4,3,2])
# Greater
print(np.greater(a,b))
# Greater and equal
print(np.greater_equal(a,b))
# Less
print(np.less(a,b))
# Less and equal
print(np.less_equal(a,b))

[False False False  True]
[False False  True  True]
[ True  True False False]
[ True  True  True False]


# Question 2

In [2]:
# To create an array consist of all elements as zeros.
import numpy as np
a=np.zeros((10,10))
print(a)
# To create an array consist of all elements as ones.
b=np.ones((10,10))
print(b)
# To create an array consist of all elements as fives.
c=np.full((10,10),5)
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


# Question 3

In [3]:
# Program for sum of all elements in array using Numpy.
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.sum(a))
# Program for sum of each column 
print(np.sum(a,axis=0))
# Program for sum of each row
print(np.sum(a,axis=1))

36
[ 6  8 10 12]
[10 26]


# Question 4

In [4]:
from scipy.special import exp10
b=np.array([[11,12,13,14],[15,16,17,18]])
# For addition
print(a+b)
# For Subtracction
print(a-b)
# For Multiplication
print(a*b)
# For Division
print(a/b)

[[12 14 16 18]
 [20 22 24 26]]
[[-10 -10 -10 -10]
 [-10 -10 -10 -10]]
[[ 11  24  39  56]
 [ 75  96 119 144]]
[[0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444]]


# Question 5

In [5]:
from scipy import linalg
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
# Sine values of an array
print(linalg.sinm(a))
# cosine values of an array
print(linalg.cosm(a))
# Tan values of an array
print(linalg.tanm(a))

[[ 0.61960655  0.081017   -0.45757255]
 [-0.12751503 -0.23178104 -0.33604706]
 [-0.87463661 -0.54457908 -0.21452156]]
[[ 0.22531486 -0.38005775  0.01456963]
 [-0.46778738  0.48834781 -0.555517  ]
 [-0.16088961 -0.64324662 -0.12560363]]
[[ 4.28672251  1.3120424  -1.66263771]
 [ 0.80873414  0.55708001  0.30542588]
 [-2.66925423 -0.19788237  2.27348948]]


# Question 6

In [6]:
import pandas as pd
import numpy as np
details={'name':['Teja','sasi','ravi','koushik','priya','sahithi','varun','ravi','uday','nikhil'],
        'score':[12.5,9,6.5,0,9,20,14.5,0,8,19],
        'attempts':[1,3,2,3,2,3,1,1,2,1],
        'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
df = pd.DataFrame(details)
print(df)

      name  score  attempts qualify
0     Teja   12.5         1     yes
1     sasi    9.0         3      no
2     ravi    6.5         2     yes
3  koushik    0.0         3      no
4    priya    9.0         2      no
5  sahithi   20.0         3     yes
6    varun   14.5         1     yes
7     ravi    0.0         1      no
8     uday    8.0         2      no
9   nikhil   19.0         1     yes


# Question  7

In [7]:
print(df[['name','score']])

      name  score
0     Teja   12.5
1     sasi    9.0
2     ravi    6.5
3  koushik    0.0
4    priya    9.0
5  sahithi   20.0
6    varun   14.5
7     ravi    0.0
8     uday    8.0
9   nikhil   19.0


# Question 8

In [8]:
import pandas as pd
details={'name':['Teja','sasi','ravi','koushik','priya','sahithi','varun','ravi','uday','nikhil'],
        'score':[12.5,9,6.5,0,9,20,14.5,0,8,19],
        'attempts':[1,3,2,3,2,3,1,1,2,1],
        'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
df = pd.DataFrame(details)
df1=pd.DataFrame({'Phone':[9381698893,1595643545,8646943212,7568712323,4569853262,8523697412,8963257412,7896541236,7896542321,8965423156],
                 'country':['India','italy','australia','africa','india','sri lanka','india','india','india','india']})
print(pd.concat([df,df1],axis=1))

      name  score  attempts qualify       Phone    country
0     Teja   12.5         1     yes  9381698893      India
1     sasi    9.0         3      no  1595643545      italy
2     ravi    6.5         2     yes  8646943212  australia
3  koushik    0.0         3      no  7568712323     africa
4    priya    9.0         2      no  4569853262      india
5  sahithi   20.0         3     yes  8523697412  sri lanka
6    varun   14.5         1     yes  8963257412      india
7     ravi    0.0         1      no  7896541236      india
8     uday    8.0         2      no  7896542321      india
9   nikhil   19.0         1     yes  8965423156      india


# Question 9

In [9]:
print(df.isna())

    name  score  attempts  qualify
0  False  False     False    False
1  False  False     False    False
2  False  False     False    False
3  False  False     False    False
4  False  False     False    False
5  False  False     False    False
6  False  False     False    False
7  False  False     False    False
8  False  False     False    False
9  False  False     False    False


# Quesion 10

In [10]:
series=pd.Series([1,2,3,4,5])
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64
